Re-add jersey-client for Jersey server
It fails to start without it with a NoClassDefFoundError.
Class org.glassfish.jersey.server.internal.inject.WebTargetValueParamProvider
depends on the `ClientConfig` class from jersey-client.