Re-add javax.annotation API for Jersey server
It fails to start without it with a NoClassDefFoundError.
Class org.glassfish.jersey.model.internal.ComponentBag depends on
the `@Priority` annotation from javax.annotation-api.