Replace fixed member ID with UUID in test read replicas
This was causing some weird exceptions in testing. Normal clusters
always generate a UUID per lifecycle for read replicas, so this
just aligns the behaviours.

There is nothing inherently wrong with having a fixed member ID and
is a path we might choose in the future, for example by having read
replicas persist a UUID.

The exceptions in the logs looked like:

```
java.lang.IllegalStateException: Duplicate key MemberId{00000000}
(attempted merging values
ReadReplicaInfo{catchupServerAddress=localhost:20020,
clientConnectorAddresses=bolt://localhost:20018,http://localhost:20019, groups=[]}
and
ReadReplicaInfo{catchupServerAddress=localhost:20020,
clientConnectorAddresses=bolt://localhost:20018,http://localhost:20019, groups=[]})
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
```